apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: docker-api
  template:
    metadata:
      labels:
        app: docker-api
    spec:
      containers:
      - name: docker-api
        image: adaobichuks/docker-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
