apiVersion: v1
kind: Service
metadata:
  name: docker-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: docker-to-nginx
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-to-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-to-nginx
  template:
    metadata:
      labels:
        app: docker-to-nginx
    spec:
      containers:
      - name: docker-to-nginx
        image: adaobichuks/docker-to-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
